### ISSUE TITLE
News tile (sidebar)

### ISSUE THREAD

**Issue by Lordpluha** [Lordpluha/GameBlog#14]
**Todo:**
- [ ] Reusables (component props)
- [ ] Hover effects
- [ ] Flexebility
- [ ] Element as links
- [ ] U can create sidebar component witch will lists this components (also reusables)

**Reference:**

![Image](https://github.com/Lordpluha/GameBlog/assets/109725756/fb300bfa-a636-41f7-aeac-af96286bcb93)

https://stopgame.ru/news
